
project_id = "wrvqqvqvwqmfdqvqmaar"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
enabled = true
enable_signup = true

[realtime]
enabled = false

[storage]
enabled = true

[vector]
enabled = true

[edge_functions]
enabled = true

[functions._shared]
verify_jwt = false

[functions.natal]
verify_jwt = false

[functions.transits]
verify_jwt = false

[functions.progressions]
verify_jwt = false

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.stripe-payment-verifier]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.stripe-checkout-handler]
verify_jwt = false

[functions.account-creator]
verify_jwt = false

[functions.subscription-linker]
verify_jwt = true

[functions.api]
verify_jwt = false

[functions.swiss]
verify_jwt = false

[functions.swissephapi]
verify_jwt = false
