project_id = "e658f804-66d4-43ba-9cca-5e3b8e536f52"

[functions.api]
verify_jwt = false

[functions.api-usage-handler]
verify_jwt = false

[functions.cleanup-orphaned-images]
verify_jwt = false

[functions.contact-form-handler]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.download-report-pdf]
verify_jwt = false

[functions.create-report]
verify_jwt = false

[functions.create-temp-report-data]
verify_jwt = false

[functions.email-check]
verify_jwt = false

[functions.email-verification]
verify_jwt = false

[functions.fetch-temp-report]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.get-payment-status]
verify_jwt = false

[functions.get-prices]
verify_jwt = false

[functions.get-report-data]
verify_jwt = false

[functions.google-place-details]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.google-speech-to-text]
verify_jwt = false

[functions.initiate-report-flow]
verify_jwt = false

[functions.keep-warm]
verify_jwt = false

[functions.log-user-error]
verify_jwt = false

[functions.outbound-messenger]
verify_jwt = false

[functions.password_token]
verify_jwt = false

[functions.process-credits]
verify_jwt = false

[functions.process-guest-report-pdf]
verify_jwt = false

[functions.process-paid-report]
verify_jwt = false

[functions.process-topup-queue]
verify_jwt = false

[functions.report-orchestrator]
verify_jwt = false

[functions.retrieve-temp-report]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.signup_token]
verify_jwt = false

[functions.standard-report-one]
verify_jwt = false

[functions.standard-report-three]
verify_jwt = false

[functions.standard-report-four]
verify_jwt = false

[functions.standard-report-two]
verify_jwt = false

[functions.standard-report]
verify_jwt = false

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.swiss]
verify_jwt = false

[functions.create-payment-session]

[functions.trigger-report-generation]

[functions.translator-edge]
verify_jwt = false

[functions.validate-promo-code]
verify_jwt = false

[functions.verification-emailer]
verify_jwt = false

[functions.verify-guest-payment]
verify_jwt = false

[functions.llm-handler]
enabled = true
verify_jwt = true
import_map = "./functions/llm-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/llm-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/llm-handler/*.html" ]

[functions.stt-handler]
enabled = true
verify_jwt = true
import_map = "./functions/stt-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stt-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stt-handler/*.html" ]

[functions.tts-handler]
enabled = true
verify_jwt = true
import_map = "./functions/tts-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/tts-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/tts-handler/*.html" ]

[functions]
  [functions.api]
    import_map = "../import_map.json"
  [functions.api-usage-handler]
    import_map = "../import_map.json"
  [functions.cleanup-orphaned-images]
    import_map = "../import_map.json"
  [functions.contact-form-handler]
    import_map = "../import_map.json"
  [functions.conversation-llm]
    import_map = "../import_map.json"
  [functions.create-checkout]
    import_map = "../import_map.json"
  [functions.create-payment-session]
    import_map = "../import_map.json"
  [functions.create-report]
    import_map = "../import_map.json"
  [functions.create-temp-report-data]
    import_map = "../import_map.json"
  [functions.download-report-pdf]
    import_map = "../import_map.json"
  [functions.email-check]
    import_map = "../import_map.json"
  [functions.email-verification]
    import_map = "../import_map.json"
  [functions.fetch-temp-report]
    import_map = "../import_map.json"
  [functions.generate-insights]
    import_map = "../import_map.json"
  [functions.get-payment-status]
    import_map = "../import_map.json"
  [functions.get-prices]
    import_map = "../import_map.json"
  [functions.get-report-data]
    import_map = "../import_map.json"
  [functions.google-place-details]
    import_map = "../import_map.json"
  [functions.google-places-autocomplete]
    import_map = "../import_map.json"
  [functions.google-speech-to-text]
    import_map = "../import_map.json"
  [functions.google-text-to-speech]
    import_map = "../import_map.json"
  [functions.initiate-report-flow]
    import_map = "../import_map.json"
  [functions.keep-warm]
    import_map = "../import_map.json"
  [functions.llm-handler]
    import_map = "../import_map.json"
  [functions.log-user-error]
    import_map = "../import_map.json"
  [functions.messages-create]
    import_map = "../import_map.json"
  [functions.outbound-messenger]
    import_map = "../import_map.json"
  [functions.password_token]
    import_map = "../import_map.json"
  [functions.process-credits]
    import_map = "../import_map.json"
  [functions.process-guest-report-pdf]
    import_map = "../import_map.json"
  [functions.process-paid-report]
    import_map = "../import_map.json"
  [functions.process-topup-queue]
    import_map = "../import_map.json"
  [functions.report-orchestrator]
    import_map = "../import_map.json"
  [functions.retrieve-temp-report]
    import_map = "../import_map.json"
  [functions.send-email]
    import_map = "../import_map.json"
  [functions.send-notification-email]
    import_map = "../import_map.json"
  [functions.signup_token]
    import_map = "../import_map.json"
  [functions.standard-report]
    import_map = "../import_map.json"
  [functions.standard-report-four]
    import_map = "../import_map.json"
  [functions.standard-report-one]
    import_map = "../import_map.json"
  [functions.standard-report-three]
    import_map = "../import_map.json"
  [functions.standard-report-two]
    import_map = "../import_map.json"
  [functions.stripe-webhook-handler]
    import_map = "../import_map.json"
  [functions.stt-handler]
    import_map = "../import_map.json"
  [functions.swiss]
    import_map = "../import_map.json"
  [functions.translator-edge]
    import_map = "../import_map.json"
  [functions.trigger-report-generation]
    import_map = "../import_map.json"
  [functions.tts-handler]
    import_map = "../import_map.json"
  [functions.tts-speak]
    import_map = "../import_map.json"
  [functions.ttss-openai]
    import_map = "../import_map.json"
  [functions.update-service-purchase-metadata]
    import_map = "../import_map.json"
  [functions.validate-promo-code]
    import_map = "../import_map.json"
  [functions.verification-emailer]
    import_map = "../import_map.json"
  [functions.verify-guest-payment]
    import_map = "../import_map.json"
