project_id = "wrvqqvqvwqmfdqvqmaar"

[functions.verify-email-token]
verify_jwt = false

[functions.verify-token]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false