# Supabase configuration
project_id = "wrvqqvqvwqmfdqvqmaar"

[api]
port               = 54321
types_email        = "types@example.com"
schemas            = ["public", "storage", "graphql_public"]
extra_search_path  = ["extensions"]
max_rows           = 1000

[db]
port          = 5432
shadow_port   = 5433
major_version = 15

[studio]
port = 54323

[storage]
file_size_limit = "10MiB"

[auth]
site_url                       = "http://localhost:3000"
jwt_expiry                     = 3600
enable_refresh_token_rotation  = true
refresh_token_reuse_interval   = 10

[auth.email]
enable_signup          = true
double_confirm_changes = true
enable_confirmations   = false

[auth.external.github]
enabled    = true
client_id  = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret     = "env(SUPABASE_AUTH_GITHUB_SECRET)"

[auth.external.google]
enabled    = true
client_id  = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret     = "env(SUPABASE_AUTH_GOOGLE_SECRET)"

[functions]
timeout = 30

# Edge-function–specific settings
[functions.standard-report]
verify_jwt = false

[functions.swiss]
verify_jwt = false
