
project_id = "wrvqqvqvwqmfdqvqmaar"

[functions.swiss]
verify_jwt = false

[functions.standard-report]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false
