
project_id = "wrvqqvqvwqmfdqvqmaar"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
webhook_enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enabled = true
double_confirm_changes = true
double_confirm_deletions = true

[auth.email.template.invite]
subject = "You have been invited"
content_path = ""

[auth.email.template.confirmation]
subject = "Confirm Your Signup"
content_path = ""

[auth.email.template.recovery]
subject = "Reset Your Password"
content_path = ""

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = ""

[auth.email.template.email_change]
subject = "Confirm Email Change"
content_path = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.microsoft]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[functions.send-notification-email]
verify_jwt = true

[functions.resend-email-change]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.contact-form-handler]
verify_jwt = false

[functions.swiss]
verify_jwt = false

[functions.standard-report]
verify_jwt = false
