
project_id = "wrvqqvqvwqmfdqvqmaar"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = false

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = false

[edge-runtime]
enabled = false

[functions]
[functions.stripe-webhook-handler]
verify_jwt = false
