
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "lovable"

[api]
# Port to use when running `supabase start`.
port = 54321
# Additional schemas to expose in your API.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search path of every request to expose tables/views.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure.
# Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use when running `supabase start`.
port = 54322
# Directing to docker when running locally
host = "db"
# The database major version to use. This has to be the same as your remote database's.
# Used to check if local migrations will work on the remote database.
major_version = 15

[studio]
# Port to use when running `supabase start`.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use when running `supabase start`.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Defaults to 10 seconds.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

[functions]
# Port to use for Supabase Functions.
port = 54328

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.process-topup-queue]
verify_jwt = false
