// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { SUPABASE_CONFIG } from '@/config/supabase-config';

const SUPABASE_URL = SUPABASE_CONFIG.url;
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_CONFIG.anonKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using generic type to allow access to all tables until types are regenerated
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});