name: Deploy Supabase Edge Functions

on:
  push:
    paths:
      - 'supabase/functions/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Supabase CLI
        run: |
          curl -L https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-x64 > supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase functions deploy --project-ref YOUR_PROJECT_ID --non-interactive
